version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: 'rabbitmq'
    restart: unless-stopped
    environment:  
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER} 
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS} 
    ports:
      - '8080:15672'
      - '5672:5672'

  mongodb:
    image: mongo
    container_name: 'mongodb'
    restart: unless-stopped
    environment:    
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}    
    ports:
      - '27017:27017'     

  shop:
    restart: unless-stopped
    build:
      context: ./shop
      dockerfile: ./Docker/Dockerfile
    environment:    
      PORT_API: ${PORT_API_SHOP}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASS: ${RABBIT_PASS}
    depends_on: 
      - rabbitmq
      - mongodb

  payment:
    restart: unless-stopped
    build:
      context: ./payment
      dockerfile: ./Docker/Dockerfile
    environment:    
      PORT_API: ${PORT_API_PAYMENT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASS: ${RABBIT_PASS}      
    depends_on: 
      - rabbitmq
      - mongodb    

  stock:
    restart: unless-stopped
    build:
      context: ./stock
      dockerfile: ./Docker/Dockerfile
    environment:    
      PORT_API: ${PORT_API_STOCK}    
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASS: ${RABBIT_PASS}        
    depends_on: 
      - rabbitmq
      - mongodb

  send:
    restart: unless-stopped
    build:
      context: ./send
      dockerfile: ./Docker/Dockerfile
    environment:    
      PORT_API: ${PORT_API_SEND}      
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASS: ${RABBIT_PASS}      
    depends_on: 
      - rabbitmq
      - mongodb