version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: 'rabbitmq'
    restart: unless-stopped
    environment:  
      RABBITMQ_DEFAULT_USER: root 
      RABBITMQ_DEFAULT_PASS: root
    ports:
      - '8080:15672'
      - '5672:5672'

  mongodb:
    image: mongo
    container_name: 'mongodb'
    restart: unless-stopped
    environment:    
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root    
    ports:
      - '27017:27017'     

  shop:
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./shop/Docker/shop.Dockerfile
    depends_on: rabbitmq

  payment:
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./payment/Docker/payment.Dockerfile
    depends_on: rabbitmq      

  stock:
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./stock/Docker/stock.Dockerfile
    depends_on: rabbitmq

  send:
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./send/Docker/send.Dockerfile
    depends_on: rabbitmq